### ISSUE TITLE
Thread 'main' panicked in 1.3.2 in Windows 10 Sandbox

### ISSUE THREAD

**Issue by truekenny** [ajour/ajour#740]
**Describe the bug**
In version 1.3.2 at starup i have error:
`[panic][ERROR] thread 'main' panicked at 'running Ajour gui: GraphicsAdapterNotFound': src\gui\mod.rs:1277`

**To Reproduce**
1. Start 1.3.2 version

**Expected behavior**
Normal run

**Software involved**
Please complete the following information:
 - OS: Windows 10 Sandbox
 - Ajour version: 1.3.2

**Additional context**
A 1.3.1 version run normal.

**Log Output**
1.3.2 log:
```
14:44:32.283 [ajour][INFO] Ajour 1.3.2 has started.
14:44:32.306 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: None,
        directories: {
            Retail: "C:\\Program Files (x86)\\World of Warcraft\\_retail_",
        },
        flavor: Retail,
    },
    addons: Addons {
        global_release_channel: Stable,
        ignored: {},
        release_channels: {},
        delete_saved_variables: false,
    },
    theme: None,
    column_config: V1 {
        local_version_width: 150,
        remote_version_width: 150,
        status_width: 85,
    },
    window_size: None,
    scale: None,
    backup_directory: None,
    backup_addons: false,
    backup_wtf: false,
    backup_config: false,
    backup_screenshots: false,
    backup_fonts: false,
    hide_ignored_addons: false,
    self_update_channel: Stable,
    weak_auras_account: {},
    alternating_row_colors: false,
    is_keybindings_enabled: true,
    language: English,
    catalog_source: None,
    auto_update: false,
    compression_format: Zip,
    zstd_compression_level: 0,
    close_to_tray: false,
    autostart: false,
    start_closed_to_tray: false,
}
14:44:32.307 [ajour::gui][DEBUG] antialiasing: false
14:44:32.323 [ajour_core::theme][DEBUG] loading user themes
14:44:32.323 [ajour_core::utility][DEBUG] checking for application update
14:44:32.329 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
14:44:32.440 [panic][ERROR] thread 'main' panicked at 'running Ajour gui: GraphicsAdapterNotFound': src\gui\mod.rs:1277
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: BaseThreadInitThunk
  17: RtlUserThreadStart

```

1.3.1 log:
```
14:45:40.925 [ajour][INFO] Ajour 1.3.1 has started.
14:45:40.943 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: None,
        directories: {
            Retail: "C:\\Program Files (x86)\\World of Warcraft\\_retail_",
        },
        flavor: Retail,
    },
    addons: Addons {
        global_release_channel: Stable,
        ignored: {},
        release_channels: {},
        delete_saved_variables: false,
    },
    theme: None,
    column_config: V1 {
        local_version_width: 150,
        remote_version_width: 150,
        status_width: 85,
    },
    window_size: None,
    scale: None,
    backup_directory: None,
    backup_addons: false,
    backup_wtf: false,
    backup_config: false,
    backup_screenshots: false,
    backup_fonts: false,
    hide_ignored_addons: false,
    self_update_channel: Stable,
    weak_auras_account: {},
    alternating_row_colors: false,
    language: English,
    catalog_source: None,
    auto_update: false,
    compression_format: Zip,
    zstd_compression_level: 0,
    close_to_tray: false,
    autostart: false,
    start_closed_to_tray: false,
}
14:45:40.943 [ajour::gui][DEBUG] antialiasing: true
14:45:41.124 [ajour_core::utility][DEBUG] checking for application update
14:45:41.124 [ajour_core::theme][DEBUG] loading user themes
14:45:41.132 [ajour_core::fs::theme][DEBUG] loaded 0 user themes
14:45:41.255 [ajour::gui::update][DEBUG] Message::ThemesLoaded(0 themes)
14:45:41.255 [ajour::gui::update][DEBUG] Message::CachesLoaded(error: false)
14:45:41.272 [ajour::gui::update][DEBUG] Message::Parse
14:45:41.275 [ajour::gui::update][DEBUG] preparing to parse addons in "C:\\Program Files (x86)\\World of Warcraft\\_retail_\\Interface/AddOns"
14:45:41.275 [ajour_core::parse][DEBUG] Retail - parsing addons folder
14:45:41.277 [ajour_core::parse][DEBUG] Retail - 66 folders in AddOns directory to parse
14:45:41.279 [ajour::gui::update][DEBUG] Message::CheckWeakAurasInstalled(Retail, is_installed: false)
14:45:41.286 [ajour_core::parse][DEBUG] Retail - 66 fingerprints: 66 cached, 0 calculated, 0 added, 0 removed
14:45:41.324 [ajour_core::parse][DEBUG] Retail - 65 addon folders successfully parsed from '.toc'
14:45:41.325 [ajour_core::parse][DEBUG] Retail - 0 valid cache entries retrieved
14:45:41.325 [ajour_core::parse][DEBUG] Retail - 65 unique fingerprints to check against curse api
14:45:41.497 [ajour::gui::update][DEBUG] Message::LatestRelease(Some("1.3.2"))
14:45:41.733 [ajour_core::catalog][DEBUG] Etag match, cached catalog is latest version
14:45:41.824 [ajour::gui::update][DEBUG] Message::CatalogDownloaded(16207 addons in catalog)
14:45:43.170 [ajour_core::parse][DEBUG] Retail - 22 curse packages fetched
14:45:43.171 [ajour_core::parse][DEBUG] Retail - 0 tukui packages fetched
14:45:43.391 [ajour_core::parse][DEBUG] Retail - 6 wowi packages fetched
14:45:43.391 [ajour_core::parse][DEBUG] Retail - 0 hub packages fetched
14:45:43.392 [ajour_core::parse][DEBUG] Retail - 0 git packages fetched
14:45:43.394 [ajour_core::parse][DEBUG] Retail - 20 addons built from curse packages
14:45:43.394 [ajour_core::parse][DEBUG] Retail - 0 addons built from tukui packages
14:45:43.395 [ajour_core::parse][DEBUG] Retail - 0 addons built from wowi packages
14:45:43.395 [ajour_core::parse][DEBUG] Retail - 0 addons built from hub packages
14:45:43.396 [ajour_core::parse][DEBUG] Retail - 0 addons built from git packages
14:45:43.396 [ajour_core::parse][DEBUG] Retail - 1 unknown addon folders
14:45:43.397 [ajour_core::parse][DEBUG] Retail - 21 addons successfully parsed
14:45:43.401 [ajour::gui::update][DEBUG] Message::ParsedAddons(Retail, 21 addons)
14:45:46.884 [ajour::gui::update][DEBUG] Message::RuntimeEvent(CloseRequested)

```

**Comment by casperstorm** [comment]
In version 1.3.2 we converted to use OpenGL rather than WGPU as we hoped it would solve some compatibility issues (#453). However it seems there's actually now a few issues with OpenGL. For now you can stick to 1.3.1, but I am curious: What GPU do you have?

@tarkah should we revert back to WGPU?

**Comment by truekenny** [comment]
On host: Geforce Gtx 980.
Inside Sandbox: Microsoft Remote Display Adapter.

**Comment by casperstorm** [comment]
@truekenny can you test this version?
[ajour.zip](https://github.com/ajour/ajour/files/7261142/ajour.zip)

**Comment by truekenny** [comment]
Same error.

```
15:41:37.491 [ajour][INFO] Ajour 1.3.2 has started.
15:41:37.508 [ajour::gui][DEBUG] config loaded:
Config {
    wow: Wow {
        directory: None,
        directories: {
            Retail: "C:\\Program Files (x86)\\World of Warcraft\\_retail_",
        },
        flavor: Retail,
    },
    addons: Addons {
        global_release_channel: Stable,
        ignored: {},
        release_channels: {},
        delete_saved_variables: false,
    },
    theme: None,
    column_config: V1 {
        local_version_width: 150,
        remote_version_width: 150,
        status_width: 85,
    },
    window_size: None,
    scale: None,
    backup_directory: None,
    backup_addons: false,
    backup_wtf: false,
    backup_config: false,
    backup_screenshots: false,
    backup_fonts: false,
    hide_ignored_addons: false,
    self_update_channel: Stable,
    weak_auras_account: {},
    alternating_row_colors: false,
    is_keybindings_enabled: true,
    language: English,
    catalog_source: None,
    auto_update: false,
    compression_format: Zip,
    zstd_compression_level: 0,
    close_to_tray: false,
    autostart: false,
    start_closed_to_tray: false,
}
15:41:37.508 [ajour::gui][DEBUG] antialiasing: false
15:41:37.613 [panic][ERROR] thread 'main' panicked at 'running Ajour gui: GraphicsAdapterNotFound': src\gui\mod.rs:1277
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: BaseThreadInitThunk
  17: RtlUserThreadStart


```
